import { useState, useEffect, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'
const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5001'
const VIEWPORTS = [
  { label: 'Desktop', width: '100%' },
  { label: 'Tablet', width: '768px' },
  { label: 'Mobile', width: '375px' },
]
export default function PreviewPage() {
  const { id: projectId } = useParams()
  const { token } = useAuth()
  const { showToast } = useToast()
  const navigate = useNavigate()
  const embedRef = useRef(null)
  const [viewport, setViewport] = useState('100%')
  const [loading, setLoading] = useState(false)
  const [embedded, setEmbedded] = useState(false)
  const [projectName, setProjectName] = useState('')
  const [error, setError] = useState('')
  async function loadAndEmbed() {
    setLoading(true)
    setError('')
    setEmbedded(false)
    try {
      // fetch project details + artifacts
      const res = await fetch(`${BASE_URL}/api/projects/${projectId}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      })
      if (!res.ok) throw new Error('Failed to load project')
      const project = await res.json()
      setProjectName(project.name || 'Project')
      const artRes = await fetch(`${BASE_URL}/api/projects/${projectId}/artifacts`, {
        headers: { 'Authorization': `Bearer ${token}` }
      })
      if (!artRes.ok) throw new Error('Failed to load artifacts')
      const artifacts = await artRes.json()
      const frontendStructure = artifacts['frontend-structure'] || ''
      const frontendComponents = artifacts['frontend-components'] || ''
      const packageArtifact = artifacts['package'] || '{}'
      // parse package.json for dependencies
      let dependencies = { 'react': '18', 'react-dom': '18', 'react-router-dom': '6' }
      try {
        const pkg = JSON.parse(packageArtifact)
        const clientDeps = pkg.client?.dependencies || pkg.dependencies || {}
        dependencies = { ...dependencies, ...clientDeps }
      } catch {}
      // load StackBlitz SDK dynamically
      const script = document.createElement('script')
      script.src = 'https://unpkg.com/@stackblitz/sdk/bundles/sdk.umd.js'
      script.onload = () => {
        const sdk = window.StackBlitzSDK
        sdk.embedProject(
          embedRef.current,
          {
            title: project.name || 'SpecForge Preview',
            description: `Generated by SpecForge`,
            template: 'create-react-app',
            files: {
              'src/App.jsx': frontendStructure || `import React from 'react';\nexport default function App() { return <h1>App</h1>; }`,
              'src/components/index.jsx': frontendComponents || `export default function Components() { return null; }`,
              'src/index.jsx': `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nReactDOM.createRoot(document.getElementById('root')).render(<App />);`,
              'public/index.html': `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${project.name}</title></head><body><div id="root"></div></body></html>`,
            },
            dependencies,
          },
          {
            openFile: 'src/App.jsx',
            view: 'preview',
            hideDevTools: true,
            height: 600,
          }
        )
        setEmbedded(true)
        setLoading(false)
      }
      script.onerror = () => {
        throw new Error('Failed to load StackBlitz SDK')
      }
      document.head.appendChild(script)
    } catch (err) {
      setError(err.message)
      setLoading(false)
    }
  }
  function copyShareLink() {
    const url = `${BASE_URL}/preview/${projectId}`
    navigator.clipboard.writeText(url)
      .then(() => showToast('Share link copied!', 'success'))
      .catch(() => showToast(`Share link: ${url}`, 'info'))
  }
  return (
    <>
      <div className="bg-grid" />
      <div className="orb orb-a" />
      <div className="orb orb-b" />
      <div className="shell">
        <nav className="topnav">
          <div className="brand-mark" onClick={() => navigate('/dashboard')} style={{ cursor:'pointer' }}>SF</div>
          <div className="brand-name" onClick={() => navigate('/dashboard')} style={{ cursor:'pointer' }}>Spec<span>Forge</span></div>
          <div style={{ marginLeft:'auto', display:'flex', gap:10, alignItems:'center' }}>
            <button onClick={() => navigate(-1)}
              style={{ background:'none', border:'1px solid var(--line2)', color:'var(--fog)',
                padding:'6px 14px', borderRadius:6, cursor:'pointer', fontSize:11,
                letterSpacing:2, textTransform:'uppercase', fontFamily:'Syne, sans-serif' }}>
              ← Back
            </button>
          </div>
        </nav>
        <div className="page-inner">
          <div className="hero-block" style={{ marginBottom:24 }}>
            <div className="hero-eyebrow">// live preview</div>
            <h1 className="hero-h">Preview {projectName && `— ${projectName}`}</h1>
            <p className="hero-sub">Your generated React app running live via StackBlitz</p>
          </div>
          {error && <div className="err-bar" style={{ marginBottom:20 }}>{error}</div>}
          {/* Toolbar */}
          <div style={{ display:'flex', alignItems:'center', gap:10, marginBottom:16, flexWrap:'wrap' }}>
            <div style={{ display:'flex', background:'var(--ink)', borderRadius:8, padding:3, gap:2 }}>
              {VIEWPORTS.map(v => (
                <button key={v.label}
                  onClick={() => setViewport(v.width)}
                  style={{ padding:'6px 14px', borderRadius:6, border:'none', cursor:'pointer',
                    background: viewport === v.width ? 'var(--ink3)' : 'transparent',
                    color: viewport === v.width ? 'var(--text)' : 'var(--fog)',
                    fontSize:10, letterSpacing:2, textTransform:'uppercase',
                    fontFamily:'Syne, sans-serif', fontWeight: viewport === v.width ? 600 : 400 }}>
                  {v.label}
                </button>
              ))}
            </div>
            <div style={{ marginLeft:'auto', display:'flex', gap:8 }}>
              {embedded && (
                <button onClick={copyShareLink}
                  style={{ background:'none', border:'1px solid var(--line2)', color:'var(--fog)',
                    padding:'6px 14px', borderRadius:6, cursor:'pointer', fontSize:11,
                    letterSpacing:2, textTransform:'uppercase', fontFamily:'Syne, sans-serif' }}>
                  ⎘ Share
                </button>
              )}
              <button
                className="proceed-btn"
                onClick={loadAndEmbed}
                disabled={loading}
                style={{ padding:'6px 20px' }}>
                {loading ? 'Loading...' : embedded ? '↺ Reload Preview' : '▶ Load Preview'}
              </button>
            </div>
          </div>
          {/* StackBlitz embed */}
          <div style={{ display:'flex', justifyContent:'center', background:'var(--ink)',
            borderRadius:12, border:'1px solid var(--line)', padding:16, minHeight:620 }}>
            {!embedded && !loading && (
              <div style={{ display:'flex', flexDirection:'column', alignItems:'center',
                justifyContent:'center', flex:1, gap:12, color:'var(--fog)' }}>
                <div style={{ fontSize:40 }}>⚡</div>
                <div style={{ fontSize:12, letterSpacing:2, textTransform:'uppercase',
                  fontFamily:'Syne, sans-serif' }}>
                  Click Load Preview to run your generated React app
                </div>
              </div>
            )}
            {loading && (
              <div style={{ display:'flex', flexDirection:'column', alignItems:'center',
                justifyContent:'center', flex:1, gap:12, color:'var(--fog)' }}>
                <div style={{ fontSize:12, letterSpacing:2, textTransform:'uppercase',
                  fontFamily:'Syne, sans-serif' }}>
                  Loading StackBlitz...
                </div>
              </div>
            )}
            <div
              ref={embedRef}
              style={{ width: viewport, height:600, border:'none', borderRadius:8,
                transition:'width 0.3s ease', display: embedded ? 'block' : 'none' }}
            />
          </div>
          <div style={{ marginTop:12, fontSize:11, color:'var(--fog)', textAlign:'center' }}>
            Powered by StackBlitz WebContainers — running your actual generated React code
          </div>
        </div>
      </div>
    </>
  )
}
