const JSZip = require('jszip')
function toSlug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}
function extractPackageJson(pkgContent, type) {
  if (!pkgContent) return '{}'
  try {
    const parsed = JSON.parse(pkgContent)
    if (parsed[type]) return JSON.stringify(parsed[type], null, 2)
  } catch {}
  // fallback: try to find the section by type keyword in raw text
  return pkgContent.slice(0, 2000)
}
async function buildProjectZip(projectName, artifacts) {
  const zip = new JSZip()
  const slug = toSlug(projectName || 'project')
  const root = zip.folder(slug)
  // --- server ---
  const server = root.folder('server')
  const serverSrc = server.folder('src')
  serverSrc.file('app.js', `const express = require('express')
const cors = require('cors')
const app = express()
app.use(cors())
app.use(express.json())
// TODO: import and mount your routes here
app.get('/health', (req, res) => res.json({ status: 'ok' }))
module.exports = app
`)
  const serverRoutes = serverSrc.folder('routes')
  serverRoutes.file('.gitkeep', '')
  const serverMiddleware = serverSrc.folder('middleware')
  serverMiddleware.file('.gitkeep', '')
  const serverConfig = serverSrc.folder('config')
  serverConfig.file('db.js', `const { Pool } = require('pg')
const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const query = (text, params) => pool.query(text, params)
module.exports = { query, pool }
`)
  const serverDb = server.folder('db')
  serverDb.file('schema.sql', artifacts.database || '-- No schema generated')
  server.file('package.json', extractPackageJson(artifacts.package, 'server'))
  server.file('.env.example', `PORT=5000
DATABASE_URL=postgresql://user:password@localhost:5432/dbname
JWT_SECRET=your_jwt_secret_here
ANTHROPIC_API_KEY=your_anthropic_key_here
`)
  server.file('index.js', `require('dotenv').config()
const app = require('./src/app')
const PORT = process.env.PORT || 5000
app.listen(PORT, () => console.log(\`Server running on port \${PORT}\`))
`)
  // --- client ---
  const client = root.folder('client')
  const clientSrc = client.folder('src')
  clientSrc.file('App.jsx', artifacts['frontend-structure'] || '// No frontend structure generated')
  const components = clientSrc.folder('components')
  components.file('index.jsx', artifacts['frontend-components'] || '// No components generated')
  clientSrc.file('index.css', `*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: system-ui, sans-serif; background: #0e0f13; color: #dde1ec; }
`)
  client.file('index.html', `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`)
  clientSrc.file('main.jsx', `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>)
`)
  client.file('package.json', extractPackageJson(artifacts.package, 'client'))
  client.file('vite.config.js', `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
export default defineConfig({ plugins: [react()] })
`)
  // --- root files ---
  root.file('.gitignore', `node_modules/
.env
dist/
build/
.DS_Store
`)
  root.file('README.md', `# ${projectName}
Generated by SpecForge.
## Setup
### Backend
\`\`\`bash
cd server
npm install
cp .env.example .env
# Edit .env with your values
npm run dev
\`\`\`
### Frontend
\`\`\`bash
cd client
npm install
npm run dev
\`\`\`
## Stack
- Frontend: React + Vite
- Backend: Node.js + Express
- Database: PostgreSQL
`)
  return await zip.generateAsync({ type: 'nodebuffer' })
}
module.exports = { buildProjectZip }
